### ISSUE TITLE
Can you specify a license?

### ISSUE THREAD

**Issue by danielktaylor** [heydovetail/editor#76]
Hi Dovetail team -

Can you add a license file to the project, so that I can understand how the software is allowed to be used? I'm hoping to use a subset of the code as a starting point for my own ProseMirror-based editor, depending on the license.

Thanks!

**Comment by bradleyayers** [comment]
Hey @danielktaylor unfortunately the repo isn't currently licensed, and we don't have any immediate plans to license it. If that changes we'll be sure to include a LICENSE file in the repo.
